### PR TITLE
Added logo files

### PR DESCRIPTION
**Pull request by roshanrahman**
Designed some logos for your consideration
Font used: *IBM Plex Mono*
Ref Issue: https://github.com/arthurpaulino/miraiml/issues/80

### CODE REVIEW

**Comment by arthurpaulino** [comment]
Oh wow, I had given up already haha!
I'm going to check your work.

**Comment by arthurpaulino** [comment]
@roshanrahman I really liked the *Group 3* one. Can you make it beginning with a capital M, please?

**Comment by roshanrahman** [comment]
Sure thing. It's updated.

**Comment by arthurpaulino** [comment]
Thank you very much for your kindness!

**Pull request merged**
